apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivolve-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ayatmoatamed/CloudDevOpsProject.git
    targetRevision: main
    path: Kubernetes
    directory:
      recurse: true
      exclude: "*.json"  
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
